wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1656848685
    t:
      1:
      - 1
      3:
      - 16
      4: 3.6.13
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 40
beta1:
  desc: null
  value: 0.5
continue_train:
  desc: null
  value: false
data_height:
  desc: null
  value: 52
data_width:
  desc: null
  value: 52
dataset_name:
  desc: null
  value: wm_811k
dataset_path_test:
  desc: null
  value: /storage/mskim/WDM/datadistbalanced/test_aug/
dataset_path_train:
  desc: null
  value: /storage/mskim/WDM/datadistbalanced/train_aug/
epochs:
  desc: null
  value: 21
freq_save_net:
  desc: null
  value: 10
freq_show_heatmap:
  desc: null
  value: 200
freq_show_img:
  desc: null
  value: 10
freq_show_loss:
  desc: null
  value: 10
gpu_id:
  desc: null
  value: '0'
lr:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
network_name:
  desc: null
  value: Resnet_18_CAM
num_test_iter:
  desc: null
  value: 5
optimizer_name:
  desc: null
  value: Adam
phase:
  desc: null
  value: train
save_path:
  desc: null
  value: ./checkpoints/pre_test_wm_811k_Resnet_18_CAM
scheduler_name:
  desc: null
  value: cosine
train_test_save_path:
  desc: null
  value: ./train_test/Resnet_18_CAM
use_cuda:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 5.0e-05
weight_name:
  desc: null
  value: Resnet_18_CAM
